import { getD1 } from "../../../db";
import { ApiError,fail,ok,requestId,safeText } from "../../../lib/api";
import { canManageDepartment,requireApiUser } from "../../../lib/authz";
import { getKnowledgeFile, hasKnowledgeFileStorage, putKnowledgeFile } from "../../../lib/knowledge-files";

const ph=(n:number)=>Array.from({length:n},()=>"?").join(",");
async function sha(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,"0")).join("");}
function json(value:unknown,fallback:unknown=[]){try{return JSON.parse(String(value));}catch{return fallback;}}

export async function GET(request:Request){const rid=requestId(request);try{const ctx=await requireApiUser();if(ctx.role==="EMPLOYEE")throw new ApiError(403,"ADMIN_REQUIRED","仅知识管理员可访问企业治理能力");const db=getD1();const scoped=ctx.role==="SUPER_ADMIN"?"1=1":`(dept_id IS NULL OR dept_id IN (${ph(ctx.deptIds.length)}))`,groupScoped=ctx.role==="SUPER_ADMIN"?"1=1":`(g.dept_id IS NULL OR g.dept_id IN (${ph(ctx.deptIds.length)}))`;const binds=ctx.role==="SUPER_ADMIN"?[]:ctx.deptIds;const [categories,groups,prompts,evalCases,evalRuns,connectors,webhooks,deliveries,backups,security,departments,tags,retention,users]=await Promise.all([
db.prepare(`SELECT * FROM knowledge_categories WHERE is_active=1 AND ${scoped} ORDER BY sort_order,name`).bind(...binds).all(),
db.prepare(`SELECT g.*,COUNT(ug.user_id) member_count,GROUP_CONCAT(ug.user_id) member_ids FROM enterprise_groups g LEFT JOIN user_groups ug ON ug.group_id=g.id WHERE g.is_active=1 AND ${groupScoped} GROUP BY g.id ORDER BY g.name`).bind(...binds).all(),
db.prepare("SELECT p.*,u.display_name creator FROM prompt_templates p JOIN users u ON u.id=p.created_by ORDER BY p.code,p.version DESC").all(),
db.prepare("SELECT * FROM rag_eval_cases WHERE is_active=1 ORDER BY id DESC").all(),db.prepare("SELECT r.*,c.question FROM rag_eval_runs r JOIN rag_eval_cases c ON c.id=r.case_id ORDER BY r.id DESC LIMIT 30").all(),
db.prepare("SELECT id,name,type,endpoint,status,last_sync_time,last_error,create_time FROM knowledge_connectors ORDER BY id DESC").all(),
db.prepare("SELECT id,name,url,events,is_active,last_status,last_delivery_time,create_time FROM webhook_endpoints ORDER BY id DESC").all(),db.prepare("SELECT * FROM webhook_deliveries ORDER BY id DESC LIMIT 30").all(),
db.prepare("SELECT * FROM backup_snapshots ORDER BY id DESC LIMIT 20").all(),db.prepare("SELECT e.*,d.title FROM security_events e LEFT JOIN documents d ON d.id=e.document_id WHERE e.status='OPEN' ORDER BY e.id DESC").all(),
db.prepare("SELECT d.*,u.display_name manager FROM departments d LEFT JOIN users u ON u.id=d.manager_user_id ORDER BY d.id").all(),db.prepare(`SELECT t.*,d.name department FROM tags t LEFT JOIN departments d ON d.id=t.dept_id WHERE ${ctx.role==="SUPER_ADMIN"?"1=1":`t.dept_id IN (${ph(ctx.deptIds.length)})`} ORDER BY t.name`).bind(...binds).all(),
db.prepare(`SELECT id,title,dept_id,retention_until,legal_hold,watermark_enabled,scan_status,dlp_findings FROM documents WHERE is_deleted=0 AND ${ctx.role==="SUPER_ADMIN"?"1=1":`dept_id IN (${ph(ctx.deptIds.length)})`} ORDER BY update_time DESC LIMIT 100`).bind(...binds).all(),
db.prepare(`SELECT DISTINCT u.id,u.display_name,ud.dept_id FROM users u JOIN user_departments ud ON ud.user_id=u.id WHERE u.status='ACTIVE' AND ${ctx.role==="SUPER_ADMIN"?"1=1":`ud.dept_id IN (${ph(ctx.deptIds.length)})`} ORDER BY u.display_name`).bind(...binds).all()
]);return ok({categories:categories.results,groups:groups.results,prompts:prompts.results,evalCases:evalCases.results,evalRuns:evalRuns.results,connectors:connectors.results,webhooks:webhooks.results,deliveries:deliveries.results,backups:backups.results,security:security.results,departments:departments.results,tags:tags.results,retention:retention.results,users:users.results},rid);}catch(error){return fail(error,rid);}}

export async function POST(request:Request){const rid=requestId(request);try{const ctx=await requireApiUser();if(ctx.role==="EMPLOYEE")throw new ApiError(403,"ADMIN_REQUIRED","仅知识管理员可执行治理操作");const p=await request.json() as Record<string,unknown>;const action=safeText(p.action,50);const db=getD1();const superOnly=()=>{if(ctx.role!=="SUPER_ADMIN")throw new ApiError(403,"SUPER_ADMIN_REQUIRED","该操作仅限超级管理员");};const audit=(detail:string)=>db.prepare("INSERT INTO audit_logs(dept_id,action,actor_user_id,actor,detail,request_id) VALUES(?,?,?,?,?,?)").bind(ctx.primaryDeptId,action,ctx.userId,ctx.displayName,detail,rid);
const managedDoc=async()=>{const id=Number(p.documentId);const d=await db.prepare("SELECT * FROM documents WHERE id=? AND is_deleted=0").bind(id).first<Record<string,unknown>>();if(!d||!canManageDepartment(ctx,Number(d.dept_id)))throw new ApiError(403,"FORBIDDEN","无权管理该资料");return d;};
if(action==="SAVE_DEPARTMENT"){superOnly();const id=Number(p.id),name=safeText(p.name,80),code=safeText(p.code,30).toUpperCase(),manager=Number(p.managerUserId)||null;if(!name||!code)throw new ApiError(400,"VALIDATION_ERROR","部门名称和编码不能为空");if(id)await db.prepare("UPDATE departments SET name=?,code=?,manager_user_id=?,parent_id=?,is_active=? WHERE id=?").bind(name,code,manager,Number(p.parentId)||null,p.isActive===false?0:1,id).run();else await db.prepare("INSERT INTO departments(name,code,manager_user_id,parent_id,is_active) VALUES(?,?,?,?,1)").bind(name,code,manager,Number(p.parentId)||null).run();await audit(`维护部门 ${name}`).run();return ok({saved:true},rid);}
if(action==="SAVE_CATEGORY"){const requestedDeptId=Number(p.deptId)||null,deptId=ctx.role==="SUPER_ADMIN"?requestedDeptId:ctx.primaryDeptId;if(deptId&&!canManageDepartment(ctx,deptId))throw new ApiError(403,"FORBIDDEN","无权管理该部门分类");const name=safeText(p.name,60),code=safeText(p.code,30).toUpperCase();if(!name||!code)throw new ApiError(400,"VALIDATION_ERROR","分类名称和编码不能为空");await db.prepare("INSERT INTO knowledge_categories(dept_id,name,code,sort_order) VALUES(?,?,?,?) ON CONFLICT(code) DO UPDATE SET name=excluded.name,dept_id=excluded.dept_id,sort_order=excluded.sort_order,is_active=1").bind(deptId,name,code,Number(p.sortOrder)||0).run();const category=await db.prepare("SELECT * FROM knowledge_categories WHERE code=?").bind(code).first();await audit(`维护分类 ${name}`).run();return ok({saved:true,category},rid);}
if(action==="DELETE_CATEGORY"){const id=Number(p.id),category=await db.prepare("SELECT * FROM knowledge_categories WHERE id=? AND is_active=1").bind(id).first<Record<string,unknown>>();if(!category)throw new ApiError(404,"NOT_FOUND","分类不存在或已删除");const deptId=Number(category.dept_id)||null;if(ctx.role!=="SUPER_ADMIN"&&(!deptId||!canManageDepartment(ctx,deptId)))throw new ApiError(403,"FORBIDDEN","无权删除该分类");const usage=deptId?await db.prepare("SELECT COUNT(*) count FROM documents WHERE category=? AND dept_id=?").bind(category.name,deptId).first<{count:number}>():await db.prepare("SELECT COUNT(*) count FROM documents WHERE category=?").bind(category.name).first<{count:number}>();if(Number(usage?.count)){await db.batch([db.prepare("UPDATE knowledge_categories SET is_active=0 WHERE id=?").bind(id),audit(`停用分类 ${category.name}，保留 ${usage?.count} 份历史资料关联`)]);return ok({deleted:true,mode:"DEACTIVATED",references:Number(usage?.count),message:`分类已停用；${usage?.count} 份历史资料保留原分类，不再用于新建资料`},rid);}await db.batch([db.prepare("DELETE FROM knowledge_categories WHERE id=?").bind(id),audit(`删除未使用分类 ${category.name}`)]);return ok({deleted:true,mode:"DELETED",references:0,message:"分类已删除并同步退出所有业务表单"},rid);}
if(action==="CREATE_GAP_TASK"){const reason=safeText(p.reason,60),detail=safeText(p.detail,500);if(!reason)throw new ApiError(400,"VALIDATION_ERROR","任务原因不能为空");await db.prepare("INSERT INTO knowledge_governance_tasks(type,status,dept_id,reporter_user_id,reason,detail) VALUES('MISSING','OPEN',?,?,?,?)").bind(ctx.primaryDeptId,ctx.userId,reason,detail).run();await audit("创建知识缺口任务："+reason).run();return ok({saved:true},rid);}
if(action==="SAVE_TAG"){let deptId=Number(p.deptId)||ctx.primaryDeptId;const documentId=Number(p.documentId)||0;if(documentId){const doc=await db.prepare("SELECT dept_id FROM documents WHERE id=? AND is_deleted=0").bind(documentId).first<{dept_id:number}>();if(!doc)throw new ApiError(404,"NOT_FOUND","目标资料不存在");deptId=Number(doc.dept_id);}if(!canManageDepartment(ctx,deptId))throw new ApiError(403,"FORBIDDEN","无权管理该部门标签");const name=safeText(p.name,50);if(!name)throw new ApiError(400,"VALIDATION_ERROR","标签不能为空");await db.prepare("INSERT OR IGNORE INTO tags(name,dept_id) VALUES(?,?)").bind(name,deptId).run();if(documentId)await db.prepare("INSERT OR IGNORE INTO document_tags(document_id,tag_id) SELECT ?,id FROM tags WHERE name=? AND dept_id=?").bind(documentId,name,deptId).run();await audit(`${documentId?`为资料 #${documentId} 标记`:"新增标签"} ${name}`).run();return ok({saved:true,linked:Boolean(documentId)},rid);}
if(action==="DELETE_TAG"){const id=Number(p.id),tag=await db.prepare("SELECT * FROM tags WHERE id=?").bind(id).first<Record<string,unknown>>();if(!tag)throw new ApiError(404,"NOT_FOUND","标签不存在");const deptId=Number(tag.dept_id)||ctx.primaryDeptId;if(!canManageDepartment(ctx,deptId))throw new ApiError(403,"FORBIDDEN","无权删除该标签");const usage=await db.prepare("SELECT COUNT(*) count FROM document_tags WHERE tag_id=?").bind(id).first<{count:number}>();if(Number(usage?.count))throw new ApiError(409,"TAG_IN_USE",`该标签仍关联 ${usage?.count} 份资料，请先调整资料标签`);await db.batch([db.prepare("DELETE FROM tags WHERE id=?").bind(id),audit(`删除未使用标签 ${tag.name}`)]);return ok({deleted:true,message:"标签已删除并同步退出上传表单"},rid);}
if(action==="SAVE_GROUP"){const requestedDeptId=Number(p.deptId)||null,deptId=ctx.role==="SUPER_ADMIN"?requestedDeptId:ctx.primaryDeptId;if(deptId&&!canManageDepartment(ctx,deptId))throw new ApiError(403,"FORBIDDEN","无权管理该部门用户组");const id=Number(p.id),name=safeText(p.name,80),code=safeText(p.code,30).toUpperCase();if(!name||!code)throw new ApiError(400,"VALIDATION_ERROR","用户组名称和编码不能为空");const result=id?await db.prepare("UPDATE enterprise_groups SET name=?,code=?,dept_id=? WHERE id=?").bind(name,code,deptId,id).run():await db.prepare("INSERT INTO enterprise_groups(name,code,dept_id) VALUES(?,?,?)").bind(name,code,deptId).run();const groupId=id||Number(result.meta.last_row_id);if(Array.isArray(p.userIds)){await db.prepare("DELETE FROM user_groups WHERE group_id=?").bind(groupId).run();for(const uid of p.userIds)await db.prepare("INSERT OR IGNORE INTO user_groups(user_id,group_id) VALUES(?,?)").bind(Number(uid),groupId).run();}const group=await db.prepare("SELECT g.*,COUNT(ug.user_id) member_count FROM enterprise_groups g LEFT JOIN user_groups ug ON ug.group_id=g.id WHERE g.id=? GROUP BY g.id").bind(groupId).first();await audit(`维护用户组 ${name}`).run();return ok({id:groupId,group},rid);}
if(action==="DELETE_GROUP"){const id=Number(p.id),group=await db.prepare("SELECT * FROM enterprise_groups WHERE id=? AND is_active=1").bind(id).first<Record<string,unknown>>();if(!group)throw new ApiError(404,"NOT_FOUND","用户组不存在或已删除");const deptId=Number(group.dept_id)||null;if(ctx.role!=="SUPER_ADMIN"&&(!deptId||!canManageDepartment(ctx,deptId)))throw new ApiError(403,"FORBIDDEN","无权删除该用户组");const refs=await db.prepare("SELECT (SELECT COUNT(*) FROM document_acl WHERE subject_type='GROUP' AND subject_id=?)+(SELECT COUNT(*) FROM space_permissions WHERE subject_type='GROUP' AND subject_id=?) count").bind(id,id).first<{count:number}>();const members=await db.prepare("SELECT COUNT(*) count FROM user_groups WHERE group_id=?").bind(id).first<{count:number}>();if(Number(refs?.count)){await db.batch([db.prepare("UPDATE enterprise_groups SET is_active=0 WHERE id=?").bind(id),audit(`停用用户组 ${group.name}，保留 ${refs?.count} 条权限关联`)]);return ok({deleted:true,mode:"DEACTIVATED",references:Number(refs?.count),message:`用户组已停用；${refs?.count} 条既有权限继续生效，不再允许新增授权`},rid);}await db.batch([db.prepare("DELETE FROM user_groups WHERE group_id=?").bind(id),db.prepare("DELETE FROM enterprise_groups WHERE id=?").bind(id),audit(`删除用户组 ${group.name}，清理 ${members?.count||0} 条成员关系`)]);return ok({deleted:true,mode:"DELETED",references:0,message:"用户组及成员关系已删除，并同步退出权限配置"},rid);}
if(action==="SAVE_PROMPT"){superOnly();const code=safeText(p.code||"enterprise_rag",40),instructions=safeText(p.instructions,12000);if(instructions.length<20)throw new ApiError(400,"VALIDATION_ERROR","Prompt 指令过短");const latest=await db.prepare("SELECT MAX(version) version FROM prompt_templates WHERE code=?").bind(code).first<{version:number}>();const version=Number(latest?.version||0)+1;await db.prepare("INSERT INTO prompt_templates(name,code,version,instructions,created_by) VALUES(?,?,?,?,?)").bind(safeText(p.name||"企业知识问答",80),code,version,instructions,ctx.userId).run();await audit(`创建 Prompt ${code} V${version}`).run();return ok({version},rid,201);}
if(action==="PUBLISH_PROMPT"){superOnly();const id=Number(p.id);const target=await db.prepare("SELECT code,version FROM prompt_templates WHERE id=?").bind(id).first<{code:string,version:number}>();if(!target)throw new ApiError(404,"NOT_FOUND","Prompt 版本不存在");await db.batch([db.prepare("UPDATE prompt_templates SET status='RETIRED' WHERE code=? AND status='PUBLISHED'").bind(target.code),db.prepare("UPDATE prompt_templates SET status='PUBLISHED',published_at=CURRENT_TIMESTAMP WHERE id=?").bind(id),audit(`发布 Prompt ${target.code} V${target.version}`)]);return ok({published:true},rid);}
if(action==="SAVE_EVAL_CASE"){superOnly();const q=safeText(p.question,500);if(q.length<2)throw new ApiError(400,"VALIDATION_ERROR","评测问题不能为空");const result=await db.prepare("INSERT INTO rag_eval_cases(question,expected_document_ids,expected_keywords,create_user_id) VALUES(?,?,?,?)").bind(q,JSON.stringify(p.expectedDocumentIds||[]),JSON.stringify(p.expectedKeywords||[]),ctx.userId).run();return ok({id:result.meta.last_row_id},rid,201);}
if(action==="RUN_EVAL"){superOnly();const promptId=Number(p.promptId)||0;const cases=await db.prepare("SELECT * FROM rag_eval_cases WHERE is_active=1").all<Record<string,unknown>>();const results:Array<Record<string,unknown>>=[];let passed=0,failed=0;for(const c of cases.results){const terms=(json(c.expected_keywords,[]) as string[]).map(String);const docs=await db.prepare("SELECT id,title,content,extracted_text FROM documents WHERE is_deleted=0 AND status='ARCHIVED_ACTIVE' ORDER BY update_time DESC LIMIT 300").all<Record<string,unknown>>();const ranked=docs.results.map(d=>{const text=`${d.title} ${d.content||d.extracted_text||""}`;return{id:Number(d.id),text,score:terms.filter(t=>text.includes(t)).length};}).sort((a,b)=>b.score-a.score).slice(0,5);const expected=(json(c.expected_document_ids,[]) as number[]).map(Number);const retrieved=ranked.map(x=>x.id);const recall=expected.length?expected.filter(id=>retrieved.includes(id)).length/expected.length:1;const keyword=terms.length?terms.filter(t=>ranked.some(x=>x.text.includes(t))).length/terms.length:1;const status=recall>=.8&&keyword>=.8?"PASSED":"FAILED";if(status==="PASSED")passed++;else failed++;await db.prepare("INSERT INTO rag_eval_runs(case_id,retrieved_document_ids,recall_score,keyword_score,status,detail) VALUES(?,?,?,?,?,?)").bind(c.id,JSON.stringify(retrieved),recall,keyword,status,`Top5=${retrieved.join(',')}`).run();results.push({caseId:c.id,question:c.question,recall:Math.round(recall*100),keyword:Math.round(keyword*100),status,retrieved});}await audit(`执行 ${cases.results.length} 条 RAG 评测`).run();return ok({total:cases.results.length,passed,failed,results},rid);}
if(action==="SAVE_CONNECTOR"){superOnly();const name=safeText(p.name,80),type=safeText(p.type,30),endpoint=safeText(p.endpoint,500),secret=safeText(p.secret,200);if(!name||!type)throw new ApiError(400,"VALIDATION_ERROR","连接器名称和类型不能为空");const result=await db.prepare("INSERT INTO knowledge_connectors(name,type,endpoint,secret_hash,status,create_user_id) VALUES(?,?,?,?,?,?)").bind(name,type,endpoint,secret?await sha(secret):"",p.enabled?"ACTIVE":"DISABLED",ctx.userId).run();await audit(`创建连接器 ${name}`).run();return ok({id:result.meta.last_row_id},rid,201);}
if(action==="TEST_CONNECTOR"){superOnly();const id=Number(p.id),c=await db.prepare("SELECT * FROM knowledge_connectors WHERE id=?").bind(id).first<Record<string,unknown>>();if(!c)throw new ApiError(404,"NOT_FOUND","连接器不存在");let error="";try{if(c.endpoint){const res=await fetch(String(c.endpoint),{method:"HEAD",signal:AbortSignal.timeout(5000)});if(!res.ok)throw new Error(`HTTP ${res.status}`);}}catch(e){error=e instanceof Error?e.message:"连接失败";}await db.prepare("UPDATE knowledge_connectors SET last_sync_time=CURRENT_TIMESTAMP,last_error=?,status=? WHERE id=?").bind(error,error?"ERROR":"ACTIVE",id).run();return ok({success:!error,error},rid);}
if(action==="SAVE_WEBHOOK"){superOnly();const name=safeText(p.name,80),url=safeText(p.url,500),secret=safeText(p.secret,200)||crypto.randomUUID();if(!name||!/^https:\/\//.test(url))throw new ApiError(400,"VALIDATION_ERROR","Webhook 名称及 HTTPS 地址必填");const result=await db.prepare("INSERT INTO webhook_endpoints(name,url,events,secret,create_user_id) VALUES(?,?,?,?,?)").bind(name,url,JSON.stringify(p.events||["DOCUMENT_PUBLISHED"]),secret,ctx.userId).run();await audit(`创建 Webhook ${name}`).run();return ok({id:result.meta.last_row_id,secret},rid,201);}
if(action==="TEST_WEBHOOK"){superOnly();const id=Number(p.id),h=await db.prepare("SELECT * FROM webhook_endpoints WHERE id=?").bind(id).first<Record<string,unknown>>();if(!h)throw new ApiError(404,"NOT_FOUND","Webhook 不存在");const body=JSON.stringify({event:"PING",time:new Date().toISOString(),requestId:rid});const signature=await sha(`${h.secret}.${body}`);let status=0,error="";try{const res=await fetch(String(h.url),{method:"POST",headers:{"content-type":"application/json","x-knowledge-signature":signature},body,signal:AbortSignal.timeout(8000)});status=res.status;if(!res.ok)error=`HTTP ${res.status}`;}catch(e){error=e instanceof Error?e.message:"投递失败";}await db.batch([db.prepare("INSERT INTO webhook_deliveries(webhook_id,event,status_code,error_message) VALUES(?,'PING',?,?)").bind(id,status,error),db.prepare("UPDATE webhook_endpoints SET last_status=?,last_delivery_time=CURRENT_TIMESTAMP WHERE id=?").bind(status,id)]);return ok({success:status>=200&&status<300,status,error},rid);}
if(action==="CREATE_BACKUP"){superOnly();const tables=["departments","users","roles","user_roles","user_departments","documents","document_versions","tags","document_tags","knowledge_spaces","knowledge_folders","prompt_templates","system_settings"];const snapshot:Record<string,unknown>={version:1,createdAt:new Date().toISOString(),tables:{}};let rows=0;for(const table of tables){const result=await db.prepare(`SELECT * FROM ${table}`).all();(snapshot.tables as Record<string,unknown>)[table]=result.results;rows+=result.results.length;}const body=JSON.stringify(snapshot),checksum=await sha(body),key=`backups/${new Date().toISOString().replace(/[:.]/g,'-')}.json`;if(!hasKnowledgeFileStorage())throw new ApiError(503,"STORAGE_UNAVAILABLE","备份存储不可用");await putKnowledgeFile(key,body,{contentType:"application/json",size:new TextEncoder().encode(body).byteLength});const result=await db.prepare("INSERT INTO backup_snapshots(object_key,checksum,row_count,status,created_by) VALUES(?,?,?,'VERIFIED',?)").bind(key,checksum,rows,ctx.userId).run();await audit(`创建并校验备份 ${key}`).run();return ok({id:result.meta.last_row_id,key,checksum,rows},rid,201);}
if(action==="VERIFY_BACKUP"){superOnly();const id=Number(p.id),b=await db.prepare("SELECT * FROM backup_snapshots WHERE id=?").bind(id).first<Record<string,unknown>>();const object=await getKnowledgeFile(String(b?.object_key||""));if(!b||!object)throw new ApiError(404,"NOT_FOUND","备份不存在");const valid=await sha(await object.text())===b.checksum;await db.prepare("UPDATE backup_snapshots SET status=? WHERE id=?").bind(valid?"VERIFIED":"CORRUPT",id).run();return ok({valid},rid);}
if(action==="SET_RETENTION"){const d=await managedDoc();const until=safeText(p.retentionUntil,30)||null,hold=p.legalHold?1:0,watermark=p.watermarkEnabled?1:0;await db.batch([db.prepare("UPDATE documents SET retention_until=?,legal_hold=?,watermark_enabled=?,update_user_id=?,update_time=CURRENT_TIMESTAMP WHERE id=?").bind(until,hold,watermark,ctx.userId,d.id),audit(`更新文档 #${d.id} 保留/留置/水印策略`)]);return ok({saved:true},rid);}
if(action==="RESOLVE_SECURITY"){const e=await db.prepare("SELECT e.*,d.dept_id FROM security_events e LEFT JOIN documents d ON d.id=e.document_id WHERE e.id=?").bind(Number(p.id)).first<Record<string,unknown>>();if(!e||!canManageDepartment(ctx,Number(e.dept_id||ctx.primaryDeptId)))throw new ApiError(403,"FORBIDDEN","无权处理该安全事件");await db.prepare("UPDATE security_events SET status='RESOLVED',resolved_at=CURRENT_TIMESTAMP WHERE id=?").bind(Number(p.id)).run();await audit(`关闭安全事件 #${p.id}`).run();return ok({resolved:true},rid);}
throw new ApiError(400,"UNKNOWN_ACTION","不支持的企业治理操作");}catch(error){return fail(error,rid);}}
