import { env } from "cloudflare:workers";

type RuntimeEnv={AI_PROVIDER?:string;AI_CHAT_MODEL?:string;AI_BASE_URL?:string;DEEPSEEK_API_KEY?:string;OPENAI_API_KEY?:string;OPENAI_CHAT_MODEL?:string};
export type Generation={text:string;provider:string;model:string;inputTokens:number;outputTokens:number};
function runtime(){return env as unknown as RuntimeEnv;}
export function chatRuntime(){const c=runtime(),provider=(c.AI_PROVIDER||"openai").toLowerCase();const deepseek=provider==="deepseek";return{provider,model:c.AI_CHAT_MODEL||(deepseek?"deepseek-v4-flash":c.OPENAI_CHAT_MODEL||"gpt-5.6-terra"),baseUrl:(c.AI_BASE_URL||(deepseek?"https://api.deepseek.com":"https://api.openai.com/v1")).replace(/\/$/,""),configured:Boolean(deepseek?c.DEEPSEEK_API_KEY:c.OPENAI_API_KEY)};}
async function requestWithRetry(url:string,init:RequestInit){let last:Response|null=null;for(let attempt=0;attempt<2;attempt++){last=await fetch(url,init);if(last.ok||![429,500,502,503,504].includes(last.status))return last;await new Promise(resolve=>setTimeout(resolve,250*(attempt+1)));}return last!;}
export async function generateChat(system:string,user:string,userId:number,options?:{temperature?:number;maxTokens?:number}):Promise<Generation|null>{const c=runtime(),info=chatRuntime(),temperature=Math.max(0,Math.min(1,Number(options?.temperature??.2))),maxTokens=Math.max(300,Math.min(4000,Number(options?.maxTokens||2200)));if(!info.configured)return null;if(info.provider==="deepseek"){const response=await requestWithRetry(`${info.baseUrl}/chat/completions`,{method:"POST",headers:{authorization:`Bearer ${c.DEEPSEEK_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({model:info.model,messages:[{role:"system",content:system},{role:"user",content:user}],thinking:{type:"disabled"},temperature,max_tokens:maxTokens,stream:false,user:`enterprise-kb-${userId}`})});if(!response.ok)throw new Error(`DEEPSEEK_CHAT_FAILED_${response.status}`);const payload=await response.json() as {choices?:Array<{message?:{content?:string}}>;usage?:{prompt_tokens?:number;completion_tokens?:number}};const text=payload.choices?.[0]?.message?.content?.trim();if(!text)throw new Error("DEEPSEEK_EMPTY_RESPONSE");return{text,provider:info.provider,model:info.model,inputTokens:Number(payload.usage?.prompt_tokens||0),outputTokens:Number(payload.usage?.completion_tokens||0)};}
const response=await requestWithRetry(`${info.baseUrl}/responses`,{method:"POST",headers:{authorization:`Bearer ${c.OPENAI_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({model:info.model,reasoning:{effort:"low"},text:{verbosity:"low"},max_output_tokens:maxTokens,safety_identifier:`enterprise-kb-${userId}`,instructions:system,input:user})});if(!response.ok)throw new Error(`OPENAI_RESPONSES_FAILED_${response.status}`);const payload=await response.json() as {output_text?:string;output?:Array<{content?:Array<{type?:string;text?:string}>}>;usage?:{input_tokens?:number;output_tokens?:number}};const text=payload.output_text||payload.output?.flatMap(x=>x.content??[]).find(x=>x.type==="output_text")?.text;if(!text)throw new Error("OPENAI_EMPTY_RESPONSE");return{text,provider:info.provider,model:info.model,inputTokens:Number(payload.usage?.input_tokens||0),outputTokens:Number(payload.usage?.output_tokens||0)};}
